import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const montserrat = localFont({
  src: [
    {
      path: './fonts/static/Montserrat-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/static/Montserrat-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/static/Montserrat-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-montserrat',
});
const vazire = localFont({
  src: [
    {
      path: './fonts/vazire.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-vazire',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const messages = await getMessages();
  return (
    <html dir={locale === 'fa' ? 'rtl' : 'ltr'} lang={locale}>
      <body
        className={`${montserrat.className} ${vazire.className} antialiased text-[#242424] bg-[#FAFAFA]`}
      >
        <NextIntlClientProvider messages={messages}>
          <div className="w-full h-screen flex items-center justify-center">
            <div className="w-[604px] shadow-custom-light rounded-3xl flex p-10 flex-col gap-8">
              {children}
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
